/* DO NOT EDIT, file generated by nestjs-i18n */

import { Path } from "nestjs-i18n";
export type I18nTranslations = {
    "mail": {
        "partials": {
            "footer": {
                "BEST_REGARDS": string;
            };
            "header": {
                "IMAGE_URL": string;
            };
        };
        "templates": {
            "confirmAttention": {
                "SUBJECT": string;
                "NAME": string;
                "INTRO": string;
                "HEADING": string;
                "INFO": string;
                "TIME": string;
                "DATE": string;
                "LOCATION": string;
                "CONFIRM_MESSAGE": string;
                "LINK_CONTENT": string;
            };
        };
    };
};
export type I18nPath = Path<I18nTranslations>;
