version: '3.8'

services:
  app:
    image: mohammadalbacha/rs4-server:latest
    ports:
      - 8080:3000
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules/
    env_file:
      - .env
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:14.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rs4
    ports:
      - 5432:5432
    volumes:
      - ./p2gsqyldata:/var/lib/postgresql/data

volumes:
  node_modules:
  p2gsqldata:
